# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: q-translator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        uv sync
    - name: build
      run: |
        cd src
        ..\.venv\Scripts\pyinstaller.exe -F -w main.py --icon=icon.ico
        cd dist
        ren main.exe q-translator.exe

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: q-translator-exe
        path: src/dist/q-translator.exe

    - name: Release executable
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        files: src/dist/q-translator.exe


